
const actionType = Object.freeze({
	 USER_LOGIN : 'USER_LOGIN',
	 FETCH_USER_LOGIN : 'FETCH_USER_LOGIN',
	 FETCH_USER_ERROR : 'FETCH_USER_ERROR',
	 FETCH_USER_SUCCESS : 'FETCH_USER_SUCCESS',
	 USER_REFRESH : 'USER_REFRESH',
	 USER_LOGOUT : 'USER_LOGOUT',
	 FETCH_PROTDUCT_CART_START :"FETCH_PROTDUCT_CART_START",
	 FETCH_PROTDUCT_CART_SUCCESS : "FETCH_PROTDUCT_CART_START",
	 FETCH_PROTDUCT_CART_FAILED: "FETCH_PROTDUCT_CART_START",
	 SUBMIT_TOTAL_MONEY_START: "SUBMIT_TOTAL_MONEY_START",
	 SUBMIT_TOTAL_MONEY_SUCCESS: "SUBMIT_TOTAL_MONEY_SUCCES",
	 SUBMIT_TOTAL_MONEY_FAILED: "SUBMIT_TOTAL_MONEY_FAILED"
})

export default actionType